name: connection_checker
description: "Simple check connection (internet) to CloudFlare or Google"
version: 1.2.4
homepage: ''

environment:
  sdk: '>=3.5.0'

dev_dependencies:
  flutter_lints: ^5.0.0